<?php
//
// File generated by Dolibarr installer 3.8.0 on 24 Sep 2015
//
// Take a look at conf.php.example file for an example of conf.php file
// and explanations for all possibles parameters.
//
/*$dolibarr_main_db_user='nanapet_user';
$dolibarr_main_db_pass='-#cLp.SMaa0J';
$dolibarr_main_db_name='nanapet_dolibarr';
$dolibarr_main_url_root='http://nanapet.com/dolibarr/htdocs';
$dolibarr_main_document_root='/home/nanapet/public_html/dolibarr/htdocs';
$dolibarr_main_data_root='/home/nanapet/public_html/dolibarr/documents';*/

$dolibarr_main_db_user='root';
$dolibarr_main_db_pass='';
$dolibarr_main_db_name='dolibarr_db';
$dolibarr_main_url_root='http://localhost/dolibarr/htdocs';
$dolibarr_main_document_root='/Applications/XAMPP/htdocs/dolibarr/htdocs';
$dolibarr_main_data_root='/Applications/XAMPP/htdocs/dolibarr/documents';

$dolibarr_main_db_host='127.0.0.1';
$dolibarr_main_db_port='3306';
$dolibarr_main_db_prefix='llx_';
$dolibarr_main_db_type='mysql';
$dolibarr_main_db_character_set='utf8';
$dolibarr_main_db_collation='utf8_unicode_ci';
$dolibarr_main_authentication='dolibarr';

// NanaPet
$dolibarr_main_db_name_nanapet='nanapet_db';

//$dolibarr_main_url_root_alt='/custom';
//$dolibarr_main_document_root_alt='C:/xampp/htdocs/dolibarr/htdocs/custom';
// Specific settings
$dolibarr_main_prod='0';
$dolibarr_nocsrfcheck='0';
$dolibarr_main_force_https='0';
$dolibarr_main_cookie_cryptkey='cf795f4cb519b1a3142d13082c6d1ca0';
$dolibarr_mailing_limit_sendbyweb='0';

//$dolibarr_lib_FPDF_PATH='';
//$dolibarr_lib_TCPDF_PATH='';
//$dolibarr_lib_FPDI_PATH='';
//$dolibarr_lib_TCPDI_PATH='';
//$dolibarr_lib_ADODB_PATH='';
//$dolibarr_lib_GEOIP_PATH='';
//$dolibarr_lib_NUSOAP_PATH='';
//$dolibarr_lib_PHPEXCEL_PATH='';
//$dolibarr_lib_ODTPHP_PATH='';
//$dolibarr_lib_ODTPHP_PATHTOPCLZIP='';
//$dolibarr_js_CKEDITOR='';
//$dolibarr_js_JQUERY='';
//$dolibarr_js_JQUERY_UI='';
//$dolibarr_js_JQUERY_FLOT='';

//$dolibarr_font_DOL_DEFAULT_TTF='';
//$dolibarr_font_DOL_DEFAULT_TTF_BOLD='';
